import overrides from "@/data/institution-overrides.json";
import type { JobLocation } from "@/lib/types";
import { normalizeCountryDisplay } from "@/lib/location-policy";

export interface InstitutionOverride {
  aliases: string[];
  applicationUrls: string[];
  excludedAliases: string[];
  address: string;
  city: string;
  country: string;
  latitude: number;
  longitude: number;
}

const OVERRIDE_TABLE = overrides as InstitutionOverride[];

function normalizeForMatch(value: string) {
  return value.replace(/\u00a0/g, " ").normalize("NFKC").replace(/\s+/g, " ").trim().toLowerCase();
}

export interface InstitutionMatch {
  address: string;
  city: string;
  country: string;
  latitude: number;
  longitude: number;
}

/**
 * Mirror of the offline build script's matching semantics: alias substring or
 * exact application-URL hit, in table order, with exclusions winning over
 * matches. The table is generated by
 * `python3 scripts/build_cpgis_demo_data.py --export-overrides`.
 */
export function matchInstitutionOverride(
  organization: string,
  applicationUrl?: string,
): InstitutionMatch | null {
  const organizationKey = normalizeForMatch(organization);
  const applicationUrlKey = applicationUrl ? normalizeForMatch(applicationUrl) : "";

  for (const override of OVERRIDE_TABLE) {
    const aliasMatch = override.aliases.some((alias) =>
      organizationKey.includes(normalizeForMatch(alias)),
    );
    const urlMatch = Boolean(applicationUrlKey) && override.applicationUrls.includes(applicationUrlKey);
    const excluded = override.excludedAliases.some((alias) =>
      organizationKey.includes(normalizeForMatch(alias)),
    );

    if ((aliasMatch || urlMatch) && !excluded) {
      const country = normalizeCountryDisplay(override.country);
      return {
        address: override.address,
        city: override.city,
        country,
        latitude: override.latitude,
        longitude: override.longitude,
      };
    }
  }

  return null;
}

export function institutionMatchToLocation(match: InstitutionMatch): JobLocation {
  const country = normalizeCountryDisplay(match.country);

  return {
    label: [match.city, country].filter(Boolean).join(", "),
    address: match.address,
    city: match.city,
    country,
    latitude: match.latitude,
    longitude: match.longitude,
  };
}
